objects/Contact/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Card_Types</valueSetName>
    </valueSet>
</CustomField>

objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>Product__c.Country__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Card_Type__c</field>
            <operation>equals</operation>
            <valueField>Product__c.CardType__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product__c/fields/ATMFeesOtherCurrencies__c.field-meta.xml
<CustomField>
    <fullName>ATMFeesOtherCurrencies__c</fullName>
    <label>ATM Fees in Other Currencies</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

objects/Product__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product__c/fields/CardType__c.field-meta.xml
<CustomField>
    <fullName>CardType__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Card_Types</valueSetName>
    </valueSet>
</CustomField>

objects/Product__c/fields/CostCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostCalendarMonth__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/ContactsServiceTest.cls
@IsTest
private class ContactsServiceTest {

    @isTest static void testGetContactInfo() {
        String recordId = createContact();
        // Set up a test request
        RestRequest request = new RestRequest();
        request.requestUri =
            'https://wise-badger-km9e2g-dev-ed.trailblaze.salesforce.com/services/apexrest/Contacts/'
            + recordId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        // Call the method to test
        ContactProperties thisContact = ContactsController.getContactByUUID();
        // Verify results
        System.assertEquals('John', thisContact.firstName);
        System.assertEquals('IT', thisContact.country);
        System.assertEquals('Black', thisContact.cardType);

    }

    @isTest static void testContactByCaseId() {
        String externalId = createContact();

        Contact ctt = [SELECT Id 
                       FROM Contact 
                       WHERE Uuid__c =:externalId]; 
        
        
        createCase(ctt.Id);

        Case cs = [SELECT Id
                   FROM Case
                   LIMIT 1];

        List<ContactProperties> cttInfo = ContactInfoController.getContacts(cs.Id);
        System.assertEquals('IT', cttInfo.get(0).country);
        System.assertEquals('Black', cttInfo.get(0).cardType);

    }

    static void createCase(Id cttId) {
        Case cs = new Case(
            Subject='Test Case',
            ContactId=cttId,
            Origin='Web' 
        );

        insert cs;
    }

    static String createContact() {       
        
        createProduct();

        Id productId = [SELECT Id FROM Product__c LIMIT 1].Id;

        // Create test record
        Contact contactTest = new Contact(
            FirstName='John',
            LastName='Doe',
            Country__c = 'IT',
            Card_Type__c = 'Black',
            Uuid__c = 'TEST-001-N26',
            Product__c = productId
            );

        insert contactTest;

        return contactTest.Uuid__c;
    }          

    static void createProduct() {
        Product__c productItBlack = new Product__c(
            Name = 'IT Black',
            Country__c = 'IT',
            CardType__c = 'Black',
            CostCalendarMonth__c = 9.90,
            ATMFeesOtherCurrencies__c = 0.00,
            CardReplacementCost__c = 6.00
        );

        insert productItBlack;

    }
}