objects/Contact/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Card_Types</valueSetName>
    </valueSet>
</CustomField>

objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Country__c</field>
            <operation>equals</operation>
            <valueField>Product__c.Country__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Card_Type__c</field>
            <operation>equals</operation>
            <valueField>Product__c.CardType__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product__c/fields/ATMFeesOtherCurrencies__c.field-meta.xml
<CustomField>
    <fullName>ATMFeesOtherCurrencies__c</fullName>
    <label>ATM Fees in Other Currencies</label>
    <precision>6</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

objects/Product__c/fields/CardReplacementCost__c.field-meta.xml
<CustomField>
    <fullName>CardReplacementCost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Product__c/fields/CostCalendarMonth__c.field-meta.xml
<CustomField>
    <fullName>CostCalendarMonth__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

classes/ContactsService.cls
public with sharing class ContactsService {
    
    public ContactProperties getContactByUUID(Set<String> setExternalIds) {
        ContactsSelector cttSelector = new ContactsSelector();
                
        return formatContactFields(cttSelector.selectById(setExternalIds));
    }

    public List<ContactProperties> getContactByCaseId(Id caseId){
        ContactsSelector cttSelector = new ContactsSelector();
        List<ContactProperties> lstCttProperties = new List<ContactProperties>();
        
        lstCttProperties.add(formatContactFields(cttSelector.selectByCaseId(caseId)));

        return lstCttProperties;
    }


    public ContactProperties formatContactFields(List<Contact> lstContacts) {

        ContactProperties cttProperties = new ContactProperties();

        if (lstContacts.get(0).id != null) {
            cttProperties.id = lstContacts.get(0).Id;
            cttProperties.uuid = lstContacts.get(0).Uuid__c;
            cttProperties.firstName = lstContacts.get(0).FirstName;
            cttProperties.lastName = lstContacts.get(0).LastName;
            cttProperties.country = lstContacts.get(0).Country__c;
            cttProperties.cardType = lstContacts.get(0).Card_Type__c;
            cttProperties.costCalendarMonth = String.valueOf(lstContacts.get(0).Product__r.CostCalendarMonth__c);
            cttProperties.atmFeeOtherCurrencies = String.valueOf(lstContacts.get(0).Product__r.ATMFeesOtherCurrencies__c);
            cttProperties.cardReplacementCost = String.valueOf(lstContacts.get(0).Product__r.CardReplacementCost__c);
        } else {
            cttProperties.description = 'No contacts found with this external Id.';
        }

        return cttProperties;
    }
}